apiVersion: v1
kind: Namespace
metadata:
  name: agent1
  labels:
    name: agent1
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: agent2
  labels:
    name: agent2
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: manager
  labels:
    name: manager
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    environment: production
